//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регист анкеты.
    /// </summary>
    // *** Start programmer edit section *** (РегистАнкеты CustomAttributes)

    // *** End programmer edit section *** (РегистАнкеты CustomAttributes)
    [AutoAltered()]
    [Caption("Регист анкеты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистАнкетыE", new string[] {
            "ДатаРегистр as \'Дата регистр\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Организация.Наименование"})]
    [MasterViewDefineAttribute("РегистАнкетыE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("РегистАнкетыL", new string[] {
            "ДатаРегистр as \'Дата регистр\'",
            "Организация.Наименование as \'Наименование\'"})]
    public class РегистАнкеты : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаРегистр = System.DateTime.Now;
        
        private IIS.Proba6.Организация fОрганизация;
        
        // *** Start programmer edit section *** (РегистАнкеты CustomMembers)

        // *** End programmer edit section *** (РегистАнкеты CustomMembers)

        
        /// <summary>
        /// ДатаРегистр.
        /// </summary>
        // *** Start programmer edit section *** (РегистАнкеты.ДатаРегистр CustomAttributes)

        // *** End programmer edit section *** (РегистАнкеты.ДатаРегистр CustomAttributes)
        public virtual System.DateTime ДатаРегистр
        {
            get
            {
                // *** Start programmer edit section *** (РегистАнкеты.ДатаРегистр Get start)

                // *** End programmer edit section *** (РегистАнкеты.ДатаРегистр Get start)
                System.DateTime result = this.fДатаРегистр;
                // *** Start programmer edit section *** (РегистАнкеты.ДатаРегистр Get end)

                // *** End programmer edit section *** (РегистАнкеты.ДатаРегистр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистАнкеты.ДатаРегистр Set start)

                // *** End programmer edit section *** (РегистАнкеты.ДатаРегистр Set start)
                this.fДатаРегистр = value;
                // *** Start programmer edit section *** (РегистАнкеты.ДатаРегистр Set end)

                // *** End programmer edit section *** (РегистАнкеты.ДатаРегистр Set end)
            }
        }
        
        /// <summary>
        /// Регист анкеты.
        /// </summary>
        // *** Start programmer edit section *** (РегистАнкеты.Организация CustomAttributes)

        // *** End programmer edit section *** (РегистАнкеты.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Proba6.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (РегистАнкеты.Организация Get start)

                // *** End programmer edit section *** (РегистАнкеты.Организация Get start)
                IIS.Proba6.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (РегистАнкеты.Организация Get end)

                // *** End programmer edit section *** (РегистАнкеты.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистАнкеты.Организация Set start)

                // *** End programmer edit section *** (РегистАнкеты.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (РегистАнкеты.Организация Set end)

                // *** End programmer edit section *** (РегистАнкеты.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистАнкетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистАнкетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистАнкетыE", typeof(IIS.Proba6.РегистАнкеты));
                }
            }
            
            /// <summary>
            /// "РегистАнкетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистАнкетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистАнкетыL", typeof(IIS.Proba6.РегистАнкеты));
                }
            }
        }
    }
}
